- include_role:
    name: docker
    tasks_from: stack_teardown
  when: clean_install

- include_role:
    name: docker
    tasks_from: stack_deploy

- include_role:
    name: docker
    tasks_from: service_update
  vars:
    options: --force
  when: not clean_install
