version: '3.8'

services:
  daemon:
    image: crazymax/swarm-cronjob
    volumes:
      - "{{ docker_socket }}:/var/run/docker.sock"
    environment:
      - "TZ={{ timezone }}"
      - "LOG_LEVEL=INFO"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
